/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppFocusRouteImport } from './routes/_app/focus'
import { Route as AppFlashcardsRouteImport } from './routes/_app/flashcards'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommandRouteImport } from './routes/_app/command'
import { Route as AppCheckinRouteImport } from './routes/_app/checkin'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAskRouteImport } from './routes/_app/ask'
import { Route as AppSubjectsIndexRouteImport } from './routes/_app/subjects.index'
import { Route as AppAskIndexRouteImport } from './routes/_app/ask.index'
import { Route as AppSubjectsSubjectIdRouteImport } from './routes/_app/subjects.$subjectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AppRoute,
} as any)
const AppAskIndexRoute = AppAskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAskRoute,
} as any)
const AppSubjectsSubjectIdRoute = AppSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AppAskRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/checkin': typeof AppCheckinRoute
  '/command': typeof AppCommandRoute
  '/dashboard': typeof AppDashboardRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/focus': typeof AppFocusRoute
  '/plan': typeof AppPlanRoute
  '/settings': typeof AppSettingsRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/ask/': typeof AppAskIndexRoute
  '/subjects/': typeof AppSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AppCalendarRoute
  '/checkin': typeof AppCheckinRoute
  '/command': typeof AppCommandRoute
  '/dashboard': typeof AppDashboardRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/focus': typeof AppFocusRoute
  '/plan': typeof AppPlanRoute
  '/settings': typeof AppSettingsRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/ask': typeof AppAskIndexRoute
  '/subjects': typeof AppSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ask': typeof AppAskRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/command': typeof AppCommandRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/focus': typeof AppFocusRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/_app/ask/': typeof AppAskIndexRoute
  '/_app/subjects/': typeof AppSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ask'
    | '/calendar'
    | '/checkin'
    | '/command'
    | '/dashboard'
    | '/flashcards'
    | '/focus'
    | '/plan'
    | '/settings'
    | '/subjects/$subjectId'
    | '/ask/'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/checkin'
    | '/command'
    | '/dashboard'
    | '/flashcards'
    | '/focus'
    | '/plan'
    | '/settings'
    | '/subjects/$subjectId'
    | '/ask'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/ask'
    | '/_app/calendar'
    | '/_app/checkin'
    | '/_app/command'
    | '/_app/dashboard'
    | '/_app/flashcards'
    | '/_app/focus'
    | '/_app/plan'
    | '/_app/settings'
    | '/_app/subjects/$subjectId'
    | '/_app/ask/'
    | '/_app/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/focus': {
      id: '/_app/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command': {
      id: '/_app/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/': {
      id: '/_app/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask/': {
      id: '/_app/ask/'
      path: '/'
      fullPath: '/ask/'
      preLoaderRoute: typeof AppAskIndexRouteImport
      parentRoute: typeof AppAskRoute
    }
    '/_app/subjects/$subjectId': {
      id: '/_app/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AppSubjectsSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAskRouteChildren {
  AppAskIndexRoute: typeof AppAskIndexRoute
}

const AppAskRouteChildren: AppAskRouteChildren = {
  AppAskIndexRoute: AppAskIndexRoute,
}

const AppAskRouteWithChildren =
  AppAskRoute._addFileChildren(AppAskRouteChildren)

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppCommandRoute: typeof AppCommandRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppFocusRoute: typeof AppFocusRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubjectsSubjectIdRoute: typeof AppSubjectsSubjectIdRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppCommandRoute: AppCommandRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppFocusRoute: AppFocusRoute,
  AppPlanRoute: AppPlanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubjectsSubjectIdRoute: AppSubjectsSubjectIdRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
